### ISSUE TITLE
Clicking the "change" logo does nothing

### ISSUE THREAD

**Issue by paulvaden** [jmatray/ThreeMusketeers#4]
Hovering over the change logo changes the color as if it can be clicked on, but clicking on it does not redirect to the home page.

**Comment by mariechristinesmet** [comment]
Thank you for pointing this out! Our team does not consider this a real failure and has decided to close this issue since our requirements spec does not indicate that our logo should redirect to the Dashboard or a certain page, and adjusting whether hovering over the logo changes its color does not affect major functionality.
