### ISSUE TITLE
Glitch up on refreshing the page

### ISSUE THREAD

**Issue by harshivcodes** [jmatray/ThreeMusketeers#5]
Refreshing the page after logging in creates a glitch on the screen. The screenshot was part of the glitch. Feel free to DM me for the video.

Reproduction Steps:
- Login to the app
- Refresh the web page
- The glitch persists on other tabs too

![image](https://user-images.githubusercontent.com/24836340/40901476-3f6f6fba-6785-11e8-9383-f3b202d3963f.png)

**Comment by mariechristinesmet** [comment]
Thank you for pointing this out! Our team has decided this is not a real failure since the site flashes the sign up/log in page but still redirects the user to the proper page once it realizes the user is signed in a second later. 

Additionally, this occurs because of Firebase: originally, the app thinks the user is not logged in so it checks Firebase servers to figure out the auth state. Once the servers respond, the current user is populated and the app shows the user as being logged in. This process does cause a slight delay. Given this is a bit trickier to fix and may completely change how our code interacts with Firebase now, we have decided we cannot fix this bug within less than 24 hours. 

See Stack Overflow for explanation of bug:
https://stackoverflow.com/questions/37370599/firebase-auth-delayed-on-refresh
